[platformio]
default_envs = m5stickcplus2

[env:m5stickcplus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200

build_unflags = 
    -std=gnu++11 
    -std=gnu++14 
    -std=c++11 
    -std=c++14

build_flags = 
    -std=gnu++17
    -Wno-unknown-pragmas

lib_ldf_mode = deep+
lib_ignore = DFRobot_GP8XXX
lib_deps =
    https://github.com/m5stack/M5StickCPlus2.git
    https://github.com/m5stack/M5Unified.git
    https://github.com/m5stack/M5GFX.git
    IRremote@^3.9.0
